name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Switch to main branch
        run: git checkout main
      - name: Pull latest changes
        run: git pull origin main
      - name: Install dependencies
        run: npm install
      - name: Build assets
        run: npm run build
