name: Laravel

on:
  push:
    branches:
      - main

jobs:
  Connect_SSH:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH and Run Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/forge/canteen-app.pp.ua
            git checkout main
            git pull origin main
